= Directus poc (proof of concept), wip
:toc:

https://docs.directus.io/contributing/running-locally.html

https://jira.vpro.nl/browse/SYS-1179



== local database

[source, bash]
----
michiel@mitulo:(poc)~/github/mihxil/directus$ psq
psql (14.8 (Homebrew))
Type "help" for help.

postgres=# create user directus with password 'admin2k';
CREATE ROLE
postgres=# create database directus;
postgres=# grant all privileges on database directus  to  directus;


michiel@mitulo:(poc,1)~/github/mihxil/directus$ pnpm --filter api cli bootstrap

----

 http://localhost:5173/


== Findings

It sais to run the latest version of node. But if I run 20, it sais that it s too new.
[source,bash]
----
michiel@mitulo:(poc)~/github/mihxil/directus$ pnpm install
Scope: all 33 workspace projects
Lockfile is up to date, resolution step is skipped
 ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)

Your Node version is incompatible with "/@azure/msal-node/1.17.2".

Expected version: 10 || 12 || 14 || 16 || 18
Got: v20.3.0

This is happening because the package's manifest has an engines.node field specified.
To fix this issue, install the required Node version.
michiel@mitulo:(poc)~/github/mihxil/directus$


michiel@mitulo:(poc)~/github/mihxil/directus$ nvm install 18
nvm use 18
pnpm install
----


Confusing is that running  `pnpm --recursive dev` seems to just start the documentation locally again. Which I could read online as well.

I've no to idea how to try something out.

It works better if you run both app and api.

I think the bootstrapping created a random passwor,d which I didn't catch.

Retry:

[11:30:07.009] INFO: No admin email provided. Defaulting to "admin@example.com"
[11:30:07.009] INFO: No admin password provided. Defaulting to "dV6Br7QG1va7"

pnpm --filter api dev
pnpm --filter app dev

 http://localhost:8080/admin/
  ➜  Network: use --host to expose


I can construct a model via the data model editor.

This just results in tables in the database, so I figure that the schema dump could serve to model in code.

== data migration

I concocted a simple script to import the 3voor12 data. See link:migrate-test/3voor12-updates.py[python script]. It imported all nearly 30 thousand items in about 10 minutes. Just the most basic fields.


== Conclusion?

- Directus is a straightforward headless cms
- It can be obtained hosted, but self hosting doesn't seem hard either
* Just run the api and app, and a database
* it's open source
* I could just import all 3voor12 updates locally. Since I was doing it myself not restrictions at all.
- Using the api seems easier then e.g. prepr. It's just a bit more forgiving. E.g. I could just use the original uuids as id's and it worked.
- It has multiple authentication features, including azure and keycloak (not tried)
- I figured some stuff out by just checking the code, the documentation was not always clear
- I think embargo functionality is just in the graphql queries, if you need that.
- Authorization seems to be on 'collection' level. I don't know if it can be based fields. At first sight it doesn't seem so.



