= Directus poc (proof of concept), wip
:toc:

https://docs.directus.io/contributing/running-locally.html

https://jira.vpro.nl/browse/SYS-1179

== Installation

=== Dependencies
* Database (postgresql)
* nvm
* pnpm (https://pnpm.io/installation)
* nodejs 18

=== Build
[source,bash]
----
nvm install 18
nvm use 18
pnpm install
pnpm build
----
For convenience set version 18 as the default:
[source,bash]
----
nvm alias default 18
----

=== Create database

[source, bash]
----
psql

postgres=# create user directus with password 'admin2k';
CREATE ROLE
postgres=# create database directus owner directus;
postgres=# grant all privileges on database directus  to  directus;
----

=== Setup .env file (already in poc branch)
In api/.env:

[source, properties]
----
HOST="0.0.0.0"
PORT=8055

DB_CLIENT="pg"
DB_HOST="localhost"
DB_PORT=5432
DB_DATABASE=directus
DB_USER=directus
DB_PASSWORD=admin2k

KEY=admin
SECRET=admin2k

ADMIN_EMAIL=digitaal-techniek@vpro.nl
ADMIN_PASSWORD=admin2k
----

=== Bootstrap database
[source, bash]
----
pnpm --filter api cli bootstrap
----

== Running
Documentation says you can do it with:
[source,bash]
----
pnpm --recursive dev
----
But with a race-condition caveat.

So run it (in two shells) with:
[source,bash]
----
pnpm --filter api dev
pnpm --filter app dev
----
This wil run the api at 8055 (as defined in .env)
The admin interface will run at 8080, http://localhost:8080/admin/[Link]

== Configuring SSO
Create a client in the sso server to be used by directus:

* Login the admin interface
* Choose realm vpro-azure
* Go to clients
* Create client with the following settings:
** Type: Openid
** Client id: directus
** Name: Directus
** Client Authentication: On
** Root Url: http://localhost:8080/
** Redirect Uris: http://localhost:8080/*

Save client and copy the client secret from the credentials tab.
Put this and the following settings in the api/.env file
[source,properties]
----
AUTH_KEYCLOAK_DRIVER="openid"
AUTH_KEYCLOAK_CLIENT_ID="directus"
AUTH_KEYCLOAK_CLIENT_SECRET="FILLMEIN"
AUTH_KEYCLOAK_ISSUER_URL="https://sso-test.vpro.nl/auth/realms/vpro-azure/.well-known/openid-configuration"
AUTH_KEYCLOAK_IDENTIFIER_KEY="email"
AUTH_KEYCLOAK_ALLOW_PUBLIC_REGISTRATION=true
AUTH_PROVIDERS: 'keycloak'
----
To remove the login for the default provider from the login screen set the following in api/.env:
[source,properties]
----
AUTH_DISABLE_DEFAULT=true
----
But only do so if you already given a user from keycloak admin rights in Directus.

== Findings

It says to run the latest version of node. But if I run 20, it says that it is too new.
[source,bash]
----
michiel@mitulo:(poc)~/github/mihxil/directus$ pnpm install
Scope: all 33 workspace projects
Lockfile is up to date, resolution step is skipped
 ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)

Your Node version is incompatible with "/@azure/msal-node/1.17.2".

Expected version: 10 || 12 || 14 || 16 || 18
Got: v20.3.0

This is happening because the package's manifest has an engines.node field specified.
To fix this issue, install the required Node version.
michiel@mitulo:(poc)~/github/mihxil/directus$


michiel@mitulo:(poc)~/github/mihxil/directus$ nvm install 18
nvm use 18
pnpm install
pnpm build
----


Confusing is that running  `pnpm --recursive dev` seems to just start the documentation locally again. Which I could read online as well.

I've no to idea how to try something out.

It works better if you run both app and api.

I think the bootstrapping created a random password, which I didn't catch.

Retry:

[11:30:07.009] INFO: No admin email provided. Defaulting to "admin@example.com"
[11:30:07.009] INFO: No admin password provided. Defaulting to "dV6Br7QG1va7"

pnpm --filter api dev
pnpm --filter app dev

 http://localhost:8080/admin/
  ➜  Network: use --host to expose


I can construct a model via the data model editor.

This just results in tables in the database, so I figure that the schema dump could serve to model in code.

== Security
Roles from keycloak are not automatically associated in Directus:
https://github.com/directus/directus/pull/18131
https://github.com/directus/directus/pull/16812
https://github.com/directus/directus/pull/11306
Dus iets gaan doen met een event action op auth.create en auth.update
Zie https://docs.directus.io/extensions/hooks.html

Multi-tenant is not implemented directly
There is talk about business rules on
https://docs.directus.io/user-guide/user-management/users-roles-permissions.html
However no hints on how to implement that. Found in Workflow doc how you can set permissions to use fields in collection to restrict actions, through custom permissions.
https://docs.directus.io/user-guide/user-management/permissions.html#configure-custom-permissions

Multi Tenant discussion
https://github.com/directus/directus/discussions/3987
https://github.com/directus/directus/discussions/9682
https://github.com/directus/directus/discussions/2687

Users only have one role.
That is a major limitation

Use a separate 'groups' field and create custom permissions based on that?
Something like this ?
https://github.com/u12206050/directus-extension-role-chooser

== Workflow
https://docs.directus.io/guides/headless-cms/approval-workflows.html
https://docs.directus.io/guides/headless-cms/schedule-content/dynamic-sites.html

== data migration

I concocted a simple script to import the 3voor12 data. See link:migrate-test/3voor12-updates.py[python script]. It imported all nearly 30 thousand items in about 10 minutes. Just the most basic fields, but in a quite straightforward manner.

== Extensibility

Directus seems to be very extensible. Let's try something here:

https://docs.directus.io/extensions/creating-extensions.html

https://github.com/npo-poms/directus-cmsselector

[source, bash]
----
michiel@mitulo:(HEAD)~/github/npo-poms/directus-cmsselector$ nvm use 18
Now using node v18.16.1 (npm v9.5.1)

npm init directus-extension@latest
----

== Interesting extra features

- Dashboarding
- An active community (e.g. on discord)


== Conclusion?

- Directus is a straightforward headless cms
- It is tightly coupled to a relational database
* I think this can be considered an advantage, since this is what we know well anyway
* We like to be able to deal with large amounts of data, which should be no problem for something like postgresql. May be it would be different if we'd be dealing with billions and billions of items, but we don't expect _that_.
- It can be obtained hosted, but self-hosting doesn't seem hard either, and may be preferable
* Just run the api and app, and a database
* it's open source
* I could just import all 3voor12 updates locally. Since I was doing it myself not restrictions at all.
- Using the api seemed easier than e.g. prepr. It's just a bit more forgiving. E.g. I could just use the original uuids as id's and it worked.
- It has multiple authentication features, including azure and keycloak (not tried)
- I figured some stuff out by just checking the code, the documentation was not always clear
- I think embargo functionality is just in the graphql queries, if you need that.
- Authorization seems to be on 'collection' level. I don't know if it can be based fields. At first sight it doesn't seem so.
- I didn't see predefined workflow, or 'kanban' boards or so, but I don't know what this is e.g. https://directus.io/blog/directus-flows-automate-complex-data-processes-for-your-digital-projects/
https://docs.directus.io/guides/headless-cms/approval-workflows.html
It seems that these kind of things are simply very flexible, and you can just set it up as you like yourself

- for multilingual content something like this could be done: https://medium.com/directus/multilingual-content-setup-in-directus-i18n-4f243f72e554




